name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-local:
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3]
        install-base: ['/', '/opt/other/']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './'
        with:
          release-version: ${{matrix.swift-version}}
          install-base: ${{matrix.install-base}}
      - name: Check installation
        run: swift --version | grep -q ${{matrix.swift-version}}

  release-master:
    if: github.event != 'pull_request'
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3]
        install-base: ['/', '/opt/other/']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/SwiftyActions@master
        with:
          release-version: ${{matrix.swift-version}}
          install-base: ${{matrix.install-base}}
      - name: Check installation
        run: swift --version | grep -q ${{matrix.swift-version}}

  branch-local:
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3]
        install-base: ['/', '/opt/other/']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './'
        with:
          branch-name: swift-${{matrix.swift-version}}-release
          version-tag: swift-${{matrix.swift-version}}-RELEASE
          install-base: ${{matrix.install-base}}
      - name: Check installation
        run: swift --version | grep -q ${{matrix.swift-version}}

  branch-master:
    if: github.event != 'pull_request'
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3]
        install-base: ['/', '/opt/other/']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/SwiftyActions@master
        with:
          branch-name: swift-${{matrix.swift-version}}-release
          version-tag: swift-${{matrix.swift-version}}-RELEASE
          install-base: ${{matrix.install-base}}
      - name: Check installation
        run: swift --version | grep -q ${{matrix.swift-version}}
