name: Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-local:
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3, 5.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './'
        id: install-swift
        with:
          release-version: ${{matrix.swift-version}}
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}

  release-master:
    if: github.event != 'pull_request'
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3, 5.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/SwiftyActions@master
        id: install-swift
        with:
          release-version: ${{matrix.swift-version}}
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}

  branch-local:
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3, 5.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: './'
        id: install-swift
        with:
          branch-name: swift-${{matrix.swift-version}}-release
          version-tag: swift-${{matrix.swift-version}}-RELEASE
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}

  branch-master:
    if: github.event != 'pull_request'
    strategy:
      matrix:
        swift-version: [5.2.2, 5.2, 5.1.3, 5.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sersoft-gmbh/SwiftyActions@master
        id: install-swift
        with:
          branch-name: swift-${{matrix.swift-version}}-release
          version-tag: swift-${{matrix.swift-version}}-RELEASE
      - name: Check installed path
        run: test -d ${{steps.install-swift.outputs.install-path}}
      - name: Check installed version
        run: swift --version | grep -q ${{matrix.swift-version}}
